// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewcaufvuzztzotdospfx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3Y2F1ZnZ1enp0em90ZG9zcGZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMjk2NTksImV4cCI6MjA2OTcwNTY1OX0.4Qt60QdJDUSuFZwHfAqaHsr3RCwUv9dZO8W7Fnl3iNY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});